spring:
  profiles:
    active: db, core, admin, wx
  message:
    encoding: UTF-8

server:
  port: 443

  ssl:
      # 证书名称
      key-store: classpath:SHA256withRSA_www.litemall.shop.jks
      #密钥库密码
      key-store-password: 2018
      key-store-type: JKS


logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  ERROR
    org.linlinjava.litemall.db:  ERROR
    org.linlinjava.litemall.admin:  ERROR
    org.linlinjava.litemall.wx:  ERROR
    org.linlinjava.litemall:  ERROR